# This is a basic workflow to help you get started with Actions
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install

      - name: Allure report
        uses: afiore/action-allure-report@v0.1.0
        with:
          results-dir: allure-results
          report-dir: target/allure-report
