# This is a basic workflow to help you get started with Actions

name: CI

workflow "build test" {

resolves = ["comchangs/action-maven"]
  on = "push"
}

action "comchangs/action-maven" {
  uses = "comchangs/action-maven@master"
  args = "clean compile test"
}
